// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const clientsTable = {
  name: "clients",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    clientName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "client_name",
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    planType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "plan_type",
    },
    monthlyBudget: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "monthly_budget",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const paymentsTable = {
  name: "payments",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    clientId: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "client_id",
    },
    amountUsd: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "amount_usd",
    },
    paymentType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "payment_type",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    paidAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "paid_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const teamMembersTable = {
  name: "teamMembers",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    username: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    department: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "team_members",
} as const;
const ticketFeedbackTable = {
  name: "ticketFeedback",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    ticketId: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "ticket_id",
    },
    rating: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    feedbackText: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "feedback_text",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ticket_feedback",
} as const;
const ticketMessagesTable = {
  name: "ticketMessages",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    ticketId: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "ticket_id",
    },
    fromClient: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "from_client",
    },
    fromTeamMemberId: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "from_team_member_id",
    },
    messageText: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "message_text",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ticket_messages",
} as const;
const ticketTypesTable = {
  name: "ticketTypes",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    typeName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "type_name",
    },
    department: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    priority: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    avgResolutionHours: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "avg_resolution_hours",
    },
  },
  primaryKey: ["id"],
  serverName: "ticket_types",
} as const;
const ticketsTable = {
  name: "tickets",
  columns: {
    id: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    clientId: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "client_id",
    },
    assignedTo: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "assigned_to",
    },
    ticketTypeId: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "ticket_type_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    priority: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    resolvedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "resolved_at",
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "closed_at",
    },
  },
  primaryKey: ["id"],
} as const;
const clientsRelationships = {
  tickets: [
    {
      sourceField: ["id"],
      destField: ["clientId"],
      destSchema: "tickets",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["clientId"],
      destSchema: "payments",
      cardinality: "many",
    },
  ],
} as const;
const paymentsRelationships = {
  client: [
    {
      sourceField: ["clientId"],
      destField: ["id"],
      destSchema: "clients",
      cardinality: "one",
    },
  ],
} as const;
const teamMembersRelationships = {
  assignedTickets: [
    {
      sourceField: ["id"],
      destField: ["assignedTo"],
      destSchema: "tickets",
      cardinality: "many",
    },
  ],
  sentMessages: [
    {
      sourceField: ["id"],
      destField: ["fromTeamMemberId"],
      destSchema: "ticketMessages",
      cardinality: "many",
    },
  ],
} as const;
const ticketFeedbackRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "tickets",
      cardinality: "one",
    },
  ],
} as const;
const ticketMessagesRelationships = {
  ticket: [
    {
      sourceField: ["ticketId"],
      destField: ["id"],
      destSchema: "tickets",
      cardinality: "one",
    },
  ],
  fromTeamMember: [
    {
      sourceField: ["fromTeamMemberId"],
      destField: ["id"],
      destSchema: "teamMembers",
      cardinality: "one",
    },
  ],
} as const;
const ticketTypesRelationships = {
  tickets: [
    {
      sourceField: ["id"],
      destField: ["ticketTypeId"],
      destSchema: "tickets",
      cardinality: "many",
    },
  ],
} as const;
const ticketsRelationships = {
  client: [
    {
      sourceField: ["clientId"],
      destField: ["id"],
      destSchema: "clients",
      cardinality: "one",
    },
  ],
  assignee: [
    {
      sourceField: ["assignedTo"],
      destField: ["id"],
      destSchema: "teamMembers",
      cardinality: "one",
    },
  ],
  ticketType: [
    {
      sourceField: ["ticketTypeId"],
      destField: ["id"],
      destSchema: "ticketTypes",
      cardinality: "one",
    },
  ],
  messages: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "ticketMessages",
      cardinality: "many",
    },
  ],
  feedback: [
    {
      sourceField: ["id"],
      destField: ["ticketId"],
      destSchema: "ticketFeedback",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    clients: clientsTable,
    payments: paymentsTable,
    teamMembers: teamMembersTable,
    ticketFeedback: ticketFeedbackTable,
    ticketMessages: ticketMessagesTable,
    ticketTypes: ticketTypesTable,
    tickets: ticketsTable,
  },
  relationships: {
    clients: clientsRelationships,
    payments: paymentsRelationships,
    teamMembers: teamMembersRelationships,
    ticketFeedback: ticketFeedbackRelationships,
    ticketMessages: ticketMessagesRelationships,
    ticketTypes: ticketTypesRelationships,
    tickets: ticketsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "clients" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["clients"] instead from "@rocicorp/zero".
 */
export type Client = Row["clients"];
/**
 * Represents a row from the "payments" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["payments"] instead from "@rocicorp/zero".
 */
export type Payment = Row["payments"];
/**
 * Represents a row from the "teamMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["teamMembers"] instead from "@rocicorp/zero".
 */
export type TeamMember = Row["teamMembers"];
/**
 * Represents a row from the "ticketFeedback" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["ticketFeedback"] instead from "@rocicorp/zero".
 */
export type TicketFeedback = Row["ticketFeedback"];
/**
 * Represents a row from the "ticketMessages" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["ticketMessages"] instead from "@rocicorp/zero".
 */
export type TicketMessage = Row["ticketMessages"];
/**
 * Represents a row from the "ticketTypes" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["ticketTypes"] instead from "@rocicorp/zero".
 */
export type TicketType = Row["ticketTypes"];
/**
 * Represents a row from the "tickets" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["tickets"] instead from "@rocicorp/zero".
 */
export type Ticket = Row["tickets"];

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
